### ISSUE TITLE
some text elements in api docs invisible against light background

### ISSUE THREAD

**Issue by ghost** [DlangScience/DlangScience.github.io#17]
Looking a the SciD api documentation, I found that some text elements have very light colors that are practically invisible against a light/white background. I traced this to some colour settings in **prettify.css** (pre pln/pun/lit, for some examples). Presumably some of these colours were chosen for light text on dark background.

![screenshot_2016-01-30_00-10-36](https://cloud.githubusercontent.com/assets/13017659/12691269/8e0f8b2a-c6ea-11e5-98d1-2f2259aefb7b.png)

![screenshot_2016-01-30_00-38-12](https://cloud.githubusercontent.com/assets/13017659/12691276/9cffc5dc-c6ea-11e5-97a8-9a8913b252f3.png)

**Comment by John-Colvin** [comment]
I noticed this a while ago and then totally forgot to fix it, thanks for
the reminder.

**Comment by John-Colvin** [comment]
https://github.com/rejectedsoftware/ddox/issues/113

**Comment by ghost** [comment]
Hmm, this may already be fixed, I'm not sure: see https://github.com/rejectedsoftware/ddox/commit/0b007bcb0dc62a406ab63c4daa1c912dedaad1e0. Maybe try upgrading ddox?

**Comment by John-Colvin** [comment]
I am using ddox 0.12.1 and we have `dub` delete the whole `api` directory before running so there shouldn't be any historical detritus. Strange...

**Comment by ghost** [comment]
Directory https://github.com/DlangScience/DlangScience.github.io/tree/master/scid/api/prettify was last updated 6 months ago.

**Comment by John-Colvin** [comment]
yes, because ddox generates it the same every time, hence git sees no change.

**Comment by ghost** [comment]
Ah, the ddox commit I mentioned was just merged into master 4 days ago.

**Comment by John-Colvin** [comment]
I’ll try with ddox master

**Comment by John-Colvin** [comment]
crashing in libdparse, running dustmite on it now

**Comment by John-Colvin** [comment]
https://github.com/rejectedsoftware/ddox/issues/115

**Comment by ghost** [comment]
After generating the site locally with `get_pages.sh` I manually copied all the directories from ddox-0.12.1/public to DlangScience.github.io/scid/api (dirs images, prettify, scripts and styles) and voila, I got light text on dark background. I guess one has to be careful to include all the css/js bits that are consistent with the ddox version used to generate the api docs.

![screenshot_2016-01-31_21-59-09](https://cloud.githubusercontent.com/assets/13017659/12704969/1e38ba8c-c867-11e5-8dd9-2e9052139ddc.png)
